website/config/routes.rb
Rails.application.routes.draw do
  root 'bounties#index'

  post 'users/new'
  get 'tags/index'

  get 'tags/show'

  get 'tags/create'

  resources :users
  resources :bounties
  resources :tags

end

website/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :hunter, class_name: "User", foreign_key: "hunter_id"
end

website/app/models/bounty.rb
class Bounty < ActiveRecord::Base
	belongs_to :poster, class_name: "User", foreign_key: "poster_id"
	has_and_belongs_to_many :hunters, class_name: "User", foreign_key: "bounty_id", :join_table => :bounties_hunters
	has_and_belongs_to_many :tags
end

website/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :bounties
end

website/app/models/user.rb
class User < ActiveRecord::Base
	has_many :answers, class_name: "Answer", foreign_key: "hunter_id"
	has_secure_password :validations => false
	has_many :bounties, class_name: "Bounty", foreign_key: "poster_id"
	has_and_belongs_to_many :huntingbounties, class_name: "Bounty", foreign_key: "user_id", :join_table => :bounties_hunters


	#validations:
	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
	validates :description, :presence => true
end

website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website/app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :set_bounty, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show]

  # GET /bounties
  # GET /bounties.json
  def index
    @bounties = Bounty.all
  end

  # GET /bounties/1
  # GET /bounties/1.json
  def show
  end

  # GET /bounties/new
  def new
    @bounty = Bounty.new
  end

  # GET /bounties/1/edit
  def edit
  end

  # POST /bounties
  # POST /bounties.json
  def create
    @bounty = Bounty.new(bounty_params)

    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, notice: 'Bounty was successfully created.' }
        format.json { render :show, status: :created, location: @bounty }
      else
        format.html { render :new }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bounties/1
  # PATCH/PUT /bounties/1.json
  def update
    respond_to do |format|
      if @bounty.update(bounty_params)
        format.html { redirect_to @bounty, notice: 'Bounty was successfully updated.' }
        format.json { render :show, status: :ok, location: @bounty }
      else
        format.html { render :edit }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bounties/1
  # DELETE /bounties/1.json
  def destroy
    @bounty.destroy
    respond_to do |format|
      format.html { redirect_to bounties_url, notice: 'Bounty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bounty
      @bounty = Bounty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bounty_params
      params.require(:bounty).permit(:poster_id, :title, :description, :deadline, :amount)
    end

    #TODO!!!!! Change login to not just set empty user but check if user is signed in
    def set_user
      @user = User.new
    end
end

website/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@tags = Tag.all
  end

  def show
  end
end

website/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :token, :wallet, :description, :last_seen)
    end
end

website/app/helpers/application_helper.rb
module ApplicationHelper
end

website/app/helpers/bounties_helper.rb
module BountiesHelper
end

website/app/helpers/tags_helper.rb
module TagsHelper
end

website/app/helpers/users_helper.rb
module UsersHelper
end

website/app/views/bounties/_form.html.erb
<%= form_for(@bounty) do |f| %>
  <% if @bounty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bounty.errors.count, "error") %> prohibited this bounty from being saved:</h2>

      <ul>
      <% @bounty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :poster_id %><br>
    <%= f.number_field :poster_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

website/app/views/bounties/edit.html.erb
<h1>Editing Bounty</h1>

<%= render 'form' %>

<%= link_to 'Show', @bounty %> |
<%= link_to 'Back', bounties_path %>

website/app/views/bounties/index.html.erb
<div class="bountyshowoff">
hi there
</div>
<div class="bountyshowoff">

  <div class="in_bountyshowoff">
    &#36;35
  </div>

</div>
<div class="bountyshowoff">
hi there
</div>

website/app/views/bounties/new.html.erb
<h1>New Bounty</h1>

<%= render 'form' %>

<%= link_to 'Back', bounties_path %>

website/app/views/bounties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poster:</strong>
  <%= @bounty.poster_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @bounty.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bounty.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @bounty.deadline %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bounty.amount %>
</p>

<%= link_to 'Edit', edit_bounty_path(@bounty) %> |
<%= link_to 'Back', bounties_path %>

website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= form_tag(:controller=> "users", :action => "create" , method: "post") do %>

  <%= label_tag(:username, "email:") %>
  <%= text_field_tag("user[email]") %>

  <%= password_field_tag("user[password]") %>

	<%= text_area_tag("user[description]","description", size: "24x6") %>

  <%= submit_tag("Register") %>
<%end%>
<%= yield %>

</body>
</html>

website/app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

website/app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

website/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :wallet %><br>
    <%= f.text_field :wallet %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :last_seen %><br>
    <%= f.datetime_select :last_seen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

website/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

website/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th>Token</th>
      <th>Wallet</th>
      <th>Description</th>
      <th>Last seen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.token %></td>
        <td><%= user.wallet %></td>
        <td><%= user.description %></td>
        <td><%= user.last_seen %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

website/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

website/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Token:</strong>
  <%= @user.token %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @user.wallet %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Last seen:</strong>
  <%= @user.last_seen %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>